### ISSUE TITLE
Silverstripe 4 Support

### ISSUE THREAD

**Issue by wilr** [jonom/silverstripe-postmark-mailer#2]
A few people have asked me about this (because my old one module for postmark points to this). 

I've documented the steps for Silverstripe 4.5 at https://gist.github.com/wilr/d32a0e83af3489538603f1b2f18dc73a for reference. Perhaps this could be included in the README (since this is first location people hit from Google)

**Comment by jonom** [comment]
Good idea. I actually documented something similar in the forum a while back: https://forum.silverstripe.org/t/using-postmark-with-swift-mailer-on-ss4-2/873 I could add links to both.
